name: C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y clang-tidy
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DBUILD_CLANG_TIDY=ON
        else
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
        fi
      shell: bash

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: build
      run: ctest -C ${{matrix.build_type}} --output-on-failure

    - name: Generate Coverage Report (Linux only)
      if: runner.os == 'Linux' && matrix.build_type == 'Release'
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov
        lcov --capture --directory build --output-file coverage.info --ignore-errors mismatch,gcov
        lcov --remove coverage.info '/usr/*' '*/tests/*' '*/examples/*' '*/nlohmann/*' --output-file coverage.info --ignore-errors mismatch,unused
        lcov --list coverage.info --ignore-errors mismatch,unused
        genhtml coverage.info --output-directory coverage_report --ignore-errors mismatch

    - name: Upload Coverage Artifact
      if: runner.os == 'Linux' && matrix.build_type == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_report/
